### ISSUE TITLE
Grunt-ify project

### ISSUE THREAD

**Issue by frapontillo** [frakbot/italiansubs-plus-plus#2]
Project currently being moved to a Grunt-based testing and building (see branch `grunt`).

**Comment by frapontillo** [comment]
A [bug](https://github.com/ragingwind/grunt-chrome-manifest/pull/7) was fixed in [`grunt-chrome-manifest`](https://github.com/ragingwind/grunt-chrome-manifest), so this may be resumed.

**Comment by rock3r** [comment]
Scheduled for release 2.0

**Comment by rock3r** [comment]
Should we close this now?

**Comment by frapontillo** [comment]
Yep.
